import { describe, expect, it } from "vitest";
import { mapUpstreamCaptions } from "@/server/services/proxy/normalize";

describe("mapUpstreamCaptions", () => {
  it("maps the Piped `subtitles` shape", () => {
    const captions = mapUpstreamCaptions(
      [
        {
          url: "https://piped.example/api/v1/captions?lang=en",
          name: "English",
          code: "en",
          autoGenerated: false,
        },
        {
          url: "https://piped.example/api/v1/captions?lang=fr",
          name: "français (auto-généré)",
          code: "fr",
          autoGenerated: true,
        },
      ],
      "https://piped.example",
    );

    expect(captions).toEqual([
      {
        label: "English",
        languageCode: "en",
        url: "https://piped.example/api/v1/captions?lang=en",
        autoGenerated: undefined,
      },
      {
        label: "français (auto-généré)",
        languageCode: "fr",
        url: "https://piped.example/api/v1/captions?lang=fr",
        autoGenerated: true,
      },
    ]);
  });

  it("resolves the relative URLs Invidious returns against the instance base", () => {
    const captions = mapUpstreamCaptions(
      [{ label: "English", language_code: "en", url: "/api/v1/captions/abc" }],
      "https://invidious.example/",
    );

    expect(captions?.[0]).toMatchObject({
      label: "English",
      languageCode: "en",
      url: "https://invidious.example/api/v1/captions/abc",
    });
  });

  it("drops unusable entries instead of failing the whole detail", () => {
    expect(
      mapUpstreamCaptions("not-an-array", "https://x.example"),
    ).toBeUndefined();
    expect(mapUpstreamCaptions([], "https://x.example")).toBeUndefined();
    // No resolvable URL, and no language code.
    expect(
      mapUpstreamCaptions(
        [{ label: "English" }, { url: "relative-without-slash", code: "en" }],
        "https://x.example",
      ),
    ).toBeUndefined();
  });

  it("dedupes tracks that share a URL", () => {
    const captions = mapUpstreamCaptions(
      [
        { url: "/c/en", code: "en", name: "English" },
        { url: "/c/en", code: "en", name: "English" },
      ],
      "https://invidious.example",
    );
    expect(captions).toHaveLength(1);
  });
});
